---
- name: Template t customize files
  gather_facts: false
  hosts: 192.168.24.53
  tasks:
    - name: "Creacion de origen-template.txt "
      template: >
        src=/origen/origen-template.txt
        dest=/destino/origen-template.txt
        owner=root
        group=root
        mode=0644
